apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nextcloud/
  - nextcloud-secrets.yaml
patches:
  - target:
      kind: PersistentVolume
      name: postgres-volume
    path: psql-pv.yaml
namespace: nextcloud-staging
