apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - volume-claim.yaml
  - ingress.yaml
  - cloudflare-tunnel-secret.yaml
  - cloudflare-configmap.yaml
  - cloudflare-deployment.yaml
